networks:
  nats:
    name: nats
    driver: bridge

volumes:
  nats-data:


services:
  stan-server:
    networks:
      - nats
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  redis-cache:
    networks:
      - nats
    image: redis:latest
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "natsdb"
      POSTGRES_USER: "natsdbuser"
      POSTGRES_PASSWORD: "deeznats"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./DB:/docker-entrypoint-initdb.d
      - nats-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
